### PR TITLE
Add Valley of the Boom

### PR DESCRIPTION
**Pull request by landergate**
## Checklist for submitting a pull request to `Movies For Hackers`:

- [x] I have carefully **read and comply** with the [Contributing Guidelines](https://github.com/k4m4/movies-for-hackers/blob/master/contributing.md) of this repo.
- [x] I have **searched** the [PRs](https://github.com/k4m4/movies-for-hackers/pulls) of this repo and believe that this is not a duplicate.

 

- **Title**: Valley of the Boom
- **Link**: https://www.imdb.com/title/tt7768092/
- **Genre**: Documentary/Drama
- **Rating**: 6.5

<br/ >

- **Description**: Docudrama crosscut with real interviews about the 1990s tech boom in the Silicon Valley.

### CODE REVIEW

**Comment by j-roc** [comment]
Yes, this tv series is essential.

**Comment by k4m4** [comment]
Hi there @landergate. Thank you for your suggestion. Could you please squash your commits into one? Thanks.

**Comment by landergate** [comment]
@k4m4 :ok_hand:

**Comment by landergate** [comment]
@k4m4 bump :shark:

**Pull request merged**
