### PR TITLE
Add Morgan

### PR DESCRIPTION
**Pull request by MorrisJobke**
## Checklist for submitting a pull request to `Movies For Hackers`:

- [x] I have carefully **read and comply** with the [Contributing Guidelines](https://github.com/k4m4/movies-for-hackers/blob/master/CONTRIBUTING.md) of this repo.
- [x] I have **searched** the [PRs](https://github.com/k4m4/movies-for-hackers/pulls) of this repo and believe that this is not a duplicate.

----

- **Title**: Morgan
- **Link**: http://www.imdb.com/title/tt4520364/
- **Genre**: Science Fiction/Thriller
- **Rating**: 5.8/10

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Rebased to resolve conflicts

**Comment by MorrisJobke** [comment]
Rebased to resolve conflict again.

@k4m4 What is the status here?

**Comment by MorrisJobke** [comment]
> @k4m4 What is the status here?

Ah :) I filled out the issue template 😉

**Comment by k4m4** [comment]
Hi there @MorrisJobke. Thank you for your contribution! :)

**Pull request merged**
