### PR TITLE
Add Hidden Figures

### PR DESCRIPTION
**Pull request by ltruchot**
## Checklist for submitting a pull request to `Movies For Hackers`:

- [x] I have carefully **read and comply** with the [Contributing Guidelines](https://github.com/k4m4/movies-for-hackers/blob/master/contributing.md) of this repo.
- [x] I have **searched** the [PRs](https://github.com/k4m4/movies-for-hackers/pulls) of this repo and believe that this is not a duplicate.

 

- **Title**: Hidden Figures
- **Link**: https://www.imdb.com/title/tt4846340
- **Genre**: Biography/Drama/History 
- **Rating**: 7.8

<br/ >

- **Description**: The story of a team of female African-American mathematicians who served a vital role in NASA during the early years of the U.S. space program.

### CODE REVIEW

**Comment by joruchan** [comment]
I endorse this one!

**Comment by styfle** [comment]
I'll endorse this one as well 👍 

In particular, [Dorthy Vaughan](https://en.wikipedia.org/wiki/Dorothy_Vaughan) was a "human computer" who was an early adopter of "machine computers" 💻

**Comment by k4m4** [comment]
Thanks for the contribution @ltruchot!

**Comment by Siisi4** [comment]
I endorse this PR !! ♥

**Pull request merged**
