### PR TITLE
Add The Lone Gunmen

### PR DESCRIPTION
**Pull request by aicoutodasilva**
- **Title**: The Lone Gunmen
- **Link**: http://www.imdb.com/title/tt0243069/
- **Genre**: Comedy, Drama, Mystery
- **Rating**:  7.5/10 

<br/ >

- **Description**: The X-Files' Lone Gunmen, their action-loving man-childish sidekick and patron, Jimmy Bond, and their sexy master thief frienemy, Yves, investigate crimes and conspiracies, often in a silly, comedic and over the top fashion.

### CODE REVIEW

**Comment by j-roc** [comment]
I endorse this, they were the hacker characters on The X-Files. Definitely belongs on this list along with the other tv shows.

**Comment by k4m4** [comment]
Hey @aicoutodasilva, could you please resolve conflicts with master? Thanks!

**Comment by k4m4** [comment]
No worries. [Read up on it](https://help.github.com/articles/resolving-a-merge-conflict-on-github/), if you'd like.

**Comment by aicoutodasilva** [comment]
@k4m4 It's a incomprehensible Travis error...

...and i don't have privileges to solve it apparently

**Comment by k4m4** [comment]
You can ignore the travis error. It's the conflicts with master that need to be resolved.

**Comment by aicoutodasilva** [comment]
@k4m4 solved at  #199

**Pull request closed without merging**
