### PR TITLE
Added Die Hard 4 or Live Free or Die Hard

### PR DESCRIPTION
**Pull request by Raavtube**
## Checklist for submitting a pull request to `Movies For Hackers`:

- [x] I have carefully **read and comply** with the [Contributing Guidelines](https://github.com/k4m4/movies-for-hackers/blob/master/contributing.md) of this repo.
- [x] I have **searched** the [PRs](https://github.com/k4m4/movies-for-hackers/pulls) of this repo and believe that this is not a duplicate.

 

- **Title**: 
- **Link**: 
- **Genre**: 
- **Rating**: 

<br/ >

- **Description**:

### CODE REVIEW

**Comment by snshn** [comment]
It's a duplicate; already in the list as "Live Free or Die Hard".

**Comment by j-roc** [comment]
already included.

**Comment by snshn** [comment]
@k4m4 please close this issue

**Comment by k4m4** [comment]
Hey @Raavtube. Thank you for your contribution. I am closing this because it seems that the list already includes "Live Free or Die Hard".

**Pull request closed without merging**
