### PR TITLE
Add show "Altered Carbon"

### PR DESCRIPTION
**Pull request by metamas**
## Checklist for submitting a pull request to `Movies For Hackers`:

- [x] I have carefully **read and comply** with the [Contributing Guidelines](https://github.com/k4m4/movies-for-hackers/blob/master/contributing.md) of this repo.
- [x] I have **searched** the [PRs](https://github.com/k4m4/movies-for-hackers/pulls) of this repo and believe that this is not a duplicate.

 

- **Title**: Altered Carbon
- **Link**: https://www.imdb.com/title/tt2261227/
- **Genre**: Science Fiction/Mystery
- **Rating**: 8.2

<br/ >

- **Description**:  Set in a future where consciousness is digitized and stored, a prisoner returns to life in a new body and must solve a mind-bending murder to win his freedom.

### CODE REVIEW

**Comment by j-roc** [comment]
Definitely belongs, a very cyberpunk story with a lot of computer related plot points.

**Comment by k4m4** [comment]
Hey @metamas, please squash your two commits into one. Thanks!

**Comment by k4m4** [comment]
@metamas, could you please squash your commits?

**Comment by metamas** [comment]
@k4m4 Apologies such a delay. I've squashed to one commit. Let me know if anything else must be done on my end.

**Comment by k4m4** [comment]
Thank you for squashing your commits. Could you please also change your commit so that only one line has been added (your current commit indicates that `Serial Experiments Lain` was removed and re-added). Also, please resolve conflicts with `master`. Thanks again!

**Pull request closed without merging**
