### PR TITLE
Add Dollhouse, Add The Lone Gunmen (TV Series)

### PR DESCRIPTION
**Pull request by ghost**
## Checklist for submitting a pull request to `Movies For Hackers`:

- [x] I have carefully **read and comply** with the [Contributing Guidelines](https://github.com/k4m4/movies-for-hackers/blob/master/contributing.md) of this repo.
- [x] I have **searched** the [PRs](https://github.com/k4m4/movies-for-hackers/pulls) of this repo and believe that this is not a duplicate.

 

- **Title**: Dollhouse  
- **Link**: https://www.imdb.com/title/tt1135300/
- **Genre**: Drama, Mystery, Sci-Fi 
- **Rating**: 7.7

<br/ >

- **Description**: A futuristic laboratory has erased the identities of lost young people, and now imprints them with the temporary identities they need to fulfill assignments for clients. 
#203

### CODE REVIEW

**Comment by k4m4** [comment]
Hi there @aicouto! Please create two different PRs for your suggestions. Thanks!

**Comment by aicouto** [comment]
ok, one by one:

1. [Dollhouse](https://github.com/k4m4/movies-for-hackers/pull/206)

**Review by k4m4 — CHANGES_REQUESTED** [review]
Please create two different PRs for your suggestions. Thanks!

**Comment by k4m4** [comment]
Closing due to no response from the PR's author.

**Pull request closed without merging**
