### PR TITLE
Add 'Devs'

### LINKED ISSUE #244: Add Devs
A computer engineer investigates the secretive development division in her company, which she believes is behind the disappearance of her boyfriend.

IMDB: https://www.imdb.com/title/tt8134186/

### PR DESCRIPTION
**Pull request by lifeparticle**
## Checklist for submitting a pull request to `Movies For Hackers`:

- [x] I have carefully **read and comply** with the [Contributing Guidelines](https://github.com/k4m4/movies-for-hackers/blob/master/contributing.md) of this repo.
- [x] I have **searched** the [PRs](https://github.com/k4m4/movies-for-hackers/pulls) of this repo and believe that this is not a duplicate.

 

- **Title**: Devs 
- **Link**: [https://www.imdb.com/title/tt8134186](https://www.imdb.com/title/tt8134186) 
- **Genre**: Drama/Mystery/Sci-Fi 
- **Rating**: 7.9 

<br/ >

- **Description**: A computer engineer investigates the secretive development division in her company, which she believes is behind the disappearance of her boyfriend. 
- Closes #244.

### CODE REVIEW

**Comment by alex-jitbit** [comment]
Came here to submit a PR for "devs"

**Comment by k4m4** [comment]
Hey @lifeparticle. Thank you for this. Please change your commit such that your suggestion is added in the correct alphabetical position.

**Comment by lifeparticle** [comment]
Hi @k4m4. My pleasure. I've changed the alphabetical position and updated the PR. Thanks!

**Comment by k4m4** [comment]
Great, thanks. Could you also squash your commits into one, please?

**Comment by lifeparticle** [comment]
Hi @k4m4. I've squashed my commits into one. Thanks!

**Comment by k4m4** [comment]
Thanks @lifeparticle!

**Pull request merged**
