### PR TITLE
Add "Summer Wars" and "The Signal"

### PR DESCRIPTION
**Pull request by PolynomialDivision**

### CODE REVIEW

**Comment by k4m4** [comment]
Hi there @PolynomialDivision. Thank you for your contribution. Please resolve all conflicts with the master branch. Thanks!

**Comment by PolynomialDivision** [comment]
@k4m4 
I resolved the conflicts... :)
Maybe were should be some alphabetical order? ^^

**Comment by k4m4** [comment]
One last thing: please separate your two suggestions into two different pull-requests. Thanks again!

**Comment by PolynomialDivision** [comment]
Ok:
#143 The Signal
#144 Summer Wars

**Pull request closed without merging**
